### ISSUE TITLE
Overhead?

### ISSUE THREAD

**Issue by NuxRo** [PaulTimmins/linux-gre-keepalive#2]
Hello,

From what I can understand, your script sets a filter and then checks every packet for keepalive.
Unless I am wrong, wouldn't this create quite a bit of overhead, especially with busy tunnels?

Thanks

**Comment by PaulTimmins** [comment]
In theory it could - in practice it doesn't because you're looking at the tunnel itself (with encapsulation removed) with the pcap filter, which then looks for a GRE packet inside that tunnel.

Cisco GRE keepalive works by sending a packet that's intended to be de-encapsulated and then resent as-is by the far end, sort of like mailing a self-addressed stamped envelope to someone.

Thus the filter of "proto gre" is only going to match GRE tunnels inside the GRE tunnel and unless you're doing something exotic (or encapsulating data for Xibit so you can tunnel while you tunnel [1]) it shouldn't match on anything. Even if it does, since it's not occurring inline (and instead via pcap) it won't add additional latency.

[1] http://knowyourmeme.com/memes/xzibit-yo-dawg

**Comment by NuxRo** [comment]
Good answer, thanks. It makes sense.

One thing that worries me is the possibility of getting attacked with GRE packets, like it happened with Krebsonsecurity last year. A flood of such packets would in theory cause the perl script to overload, isn't it?

**Comment by PaulTimmins** [comment]
The script will only overload if the packets are GRE inside GRE that matches the linux tunneling implementation settings. So they'd have to know your far end, spoof that IP, send it to you and have GRE inside of it, and then the perl script would have to do something.

It's implemented as a event loop - the packet filter is compiled by either libpcap or bpf, and runs in C code in libpcap, only coming out to the perl script when it sees GRE that's decapsulated by the kernel containing another GRE packet.

That's a pretty specific attack vector, and the main advantage would be to kill your tunnel keepalive (which would take a substantial amount of packets, enough to overflow libpcap's buffer while we process them to the point where we drop multiple GRE keepalives.).

It's probably easier to just overflow the host with ICMP, NTP queries, DNS responses, or any other unicast connectionless flow at that point.

**Comment by NuxRo** [comment]
Thanks Paul
